version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      - "dev.containers.forward-ports=5672,15672"
      - "dev.containers.port-visibility.5672=private"
      - "dev.containers.port-visibility.15672=public"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  calculation:
    build:
      context: .
      dockerfile: Dockerfile.calculation
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "5001:8080"
    labels:
      - "dev.containers.forward-ports=5001"
      - "dev.containers.port-visibility.5001=public"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "5000:8080"
    labels:
      - "dev.containers.forward-ports=5000"
      - "dev.containers.port-visibility.5000=public"
    depends_on:
      - orchestrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:80"
    labels:
      - "dev.containers.forward-ports=3000" 
      - "dev.containers.port-visibility.3000=public"
    depends_on:
      - gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf