version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  calculation:
    build:
      context: .
      dockerfile: Dockerfile.calculation
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "5000:8080"
    depends_on:
      - orchestrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:80"
    depends_on:
      - gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf